### ISSUE TITLE
scssphp 1.7

### ISSUE THREAD

**Issue by adixon** [civicrm/composer-compile-lib#2]
I'm using this in a D8/composer install and composer upgrade is pulling in version 1.7 (was 1.6) which gives this error when running the compile task:

<code><pre>
> @php -r 'require_once '\''/var/www/drupal/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL::copy('\''../../bower_components/select2/select2-bootstrap.css'\'', '\''extern/select2/select2-bootstrap.scss'\'');'
> @php -r 'require_once '\''/var/www/drupal/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::scss($GLOBALS[\Civi\CompilePlugin\TaskTransfer::GLOBAL_VAR]);'
Script @php -r 'require_once '\''/var/www/drupal/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::scss($GLOBALS[\Civi\CompilePlugin\TaskTransfer::GLOBAL_VAR]);' handling the shell-runner event returned with error code 255

Fatal error: Uncaught ScssPhp\ScssPhp\Exception\SassScriptException: $amount: Expected 5% to be within 0% and 1% in /var/www/drupal/vendor/scssphp/scssphp/src/Exception/SassScriptException.php:30
Stack trace:
#0 /var/www/drupal/vendor/scssphp/scssphp/src/Node/Number.php(265): ScssPhp\ScssPhp\Exception\SassScriptException::forArgument('Expected 5% to ...', 'amount')
#1 /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php(8450): ScssPhp\ScssPhp\Node\Number->valueInRange(0, 1, 'amount')
#2 /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php(8459): ScssPhp\ScssPhp\Compiler->libOpacify(Array)
#3 /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php(6193): ScssPhp\ScssPhp\Compiler->libFadeIn(Array, Array)
#4 /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php(3662): ScssPhp\ScssPhp\Compiler->callNativeFunction('fadein', Array, NULL, Array)
#5 /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php(3588): ScssPhp\ScssPhp\Compiler->fncall(Array, Array)
#6 /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php(2928): in /var/www/drupal/vendor/scssphp/scssphp/src/Compiler.php on line 553
Subcommand @composer compile  returned with error code 255

                                                              
  [RuntimeException]                                          
  Subcommand @composer compile  returned with error code 255  
</pre></code>

**Comment by colemanw** [comment]
Did you see this? https://github.com/civicrm/civicrm-core/pull/21502

**Comment by adixon** [comment]
Yup, thanks!

**Comment by colemanw** [comment]
Please comment on that PR if it works for you @adixon so we can get it merged :)
